<a href="https://colab.research.google.com/github/Yooyoo95/Tools/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline


What is PyTorch?
================

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

-  NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
-  최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

Getting Started
---------------

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.



In [ ]:
from __future__ import print_function
import torch

torch.__version__

'1.7.0+cu101'

초기화되지 않은 5x3 행렬을 생성합니다:



In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[8.0759e+33, 3.0880e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0880e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.7598e+33]])


무작위로 초기화된 행렬을 생성합니다:



In [ ]:
x = torch.randn(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[ 0.4998, -0.0123,  1.2065],
        [ 0.4659, -1.1119, -1.0469],
        [ 0.3311,  0.5770, -0.9808],
        [-1.6933, -0.4311,  1.7591],
        [ 0.3346,  0.6398, -0.9855]])
tensor([[0.4225, 0.6696, 0.4458],
        [0.5661, 0.1570, 0.6661],
        [0.9700, 0.3892, 0.5740],
        [0.8643, 0.8190, 0.6379],
        [0.4663, 0.0164, 0.3621]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:



In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성합니다:



In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 
이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.


In [ ]:
x = xe.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8039, -0.0473, -0.2606],
        [-0.6666, -0.2164,  1.5497],
        [-0.0673, -0.6175,  1.4867],
        [ 1.8226, -0.9508,  2.0158],
        [ 1.1701, -1.5394, -0.1466]])


행렬의 크기를 구합니다:



In [ ]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])



덧셈: 문법1

In [ ]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[8.0759e+33, 3.0880e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0880e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.7598e+33]])
tensor([[0.4487, 0.6315, 0.0037],
        [0.5335, 0.4627, 0.2166],
        [0.4204, 0.5041, 0.9803],
        [0.7277, 0.1691, 0.2528],
        [0.1945, 0.3890, 0.1933]])
tensor([[8.0759e+33, 6.3154e-01, 3.7315e-03],
        [5.3345e-01,        nan, 2.1659e-01],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [1.9454e-01, 7.0374e+22, 2.7598e+33]])


덧셈: 문법2



In [ ]:
print(torch.add(x, y))

tensor([[8.0759e+33, 6.3154e-01, 3.7315e-03],
        [5.3345e-01,        nan, 2.1659e-01],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [1.9454e-01, 7.0374e+22, 2.7598e+33]])


덧셈: 결과 tensor를 인자로 제공


In [ ]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[8.0760e+33, 3.0880e-41, 1.4714e-43],
        [1.5414e-43, 1.6255e-43, 5.6052e-44],
        [1.5975e-43, 1.4153e-43, 1.6115e-43],
        [1.6395e-43, 1.5134e-43, 1.6255e-43],
        [5.7453e-44, 2.7598e+33, 2.7598e+33]])
tensor([[8.0759e+33, 6.3154e-01, 3.7315e-03],
        [5.3345e-01,        nan, 2.1659e-01],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [1.9454e-01, 7.0374e+22, 2.7598e+33]])


덧셈: 바꿔치기(In-place) 방식


In [ ]:
# adds x to y
print(y)
y.add_(x)
print(y)

tensor([[8.0759e+33, 6.3154e-01, 3.7315e-03],
        [5.3345e-01,        nan, 2.1659e-01],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [1.9454e-01, 7.0374e+22, 2.7598e+33]])
tensor([[1.6152e+34, 6.3154e-01, 3.7315e-03],
        [5.3345e-01,        nan, 2.1659e-01],
        [2.3157e+27, 2.2723e+30, 1.4309e+23],
        [9.1656e+30, 2.4242e+04, 1.4369e+23],
        [1.9454e-01, 1.4075e+23, 5.5197e+33]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다.<p>
예: x.copy_(y), x.t_() 는 x 를 변경합니다.

<p>
NumPy스러운 인덱싱 표기 방법을 사용할 수도 있습니다!


In [ ]:
print(x)
print(x[:, 1])

tensor([[-0.8039, -0.0473, -0.2606],
        [-0.6666, -0.2164,  1.5497],
        [-0.0673, -0.6175,  1.4867],
        [ 1.8226, -0.9508,  2.0158],
        [ 1.1701, -1.5394, -0.1466]])
tensor([-0.0473, -0.2164, -0.6175, -0.9508, -1.5394])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:


In [ ]:

x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = y.view(-1, 2)  # the size -1 is inferred from other dimensions
print(y)
print(z)
print(y.size(), z.size())

tensor([[-0.6237,  0.0898, -0.3996, -1.0912],
        [-0.0554, -0.3758,  0.0531, -0.7380],
        [ 0.9045,  0.3169, -1.4218,  0.3854],
        [ 0.4862,  1.7625,  1.3723, -0.6708]])
tensor([-0.6237,  0.0898, -0.3996, -1.0912, -0.0554, -0.3758,  0.0531, -0.7380,
         0.9045,  0.3169, -1.4218,  0.3854,  0.4862,  1.7625,  1.3723, -0.6708])
tensor([[-0.6237,  0.0898],
        [-0.3996, -1.0912],
        [-0.0554, -0.3758],
        [ 0.0531, -0.7380],
        [ 0.9045,  0.3169],
        [-1.4218,  0.3854],
        [ 0.4862,  1.7625],
        [ 1.3723, -0.6708]])
torch.Size([16]) torch.Size([8, 2])


In [ ]:
z = y.view(-1,5)

RuntimeError: ignored

만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.



In [ ]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())


tensor([1.1069])
<class 'torch.Tensor'> <class 'float'>
1.10688054561615


**읽을 거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>` 에 설명되어 있습니다.

NumPy 변환(Bridge)
------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

- Torch Tensor를 NumPy 배열로 변환하기



In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


 - NumPy 배열을 Torch Tensor로 변환하기  
 
NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [ ]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

CUDA Tensors
------------

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [ ]:
import torch

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.

x = torch.rand(4,4)
if torch.cuda.is_available():
    device = "cuda:0" # torch.device("cuda:0")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    print(y)


    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.4512, 1.0800, 1.8194, 1.3981],
        [1.3423, 1.5176, 1.6927, 1.8044],
        [1.6748, 1.4634, 1.7604, 1.0744],
        [1.3394, 1.9641, 1.3050, 1.7403]], device='cuda:0')
tensor([[1.4512, 1.0800, 1.8194, 1.3981],
        [1.3423, 1.5176, 1.6927, 1.8044],
        [1.6748, 1.4634, 1.7604, 1.0744],
        [1.3394, 1.9641, 1.3050, 1.7403]], dtype=torch.float64)


In [ ]:
x = x.cuda()